"""Write one doc page per v2 component, from the config keys it declares.

    .venv/bin/python scripts/gen_v2_docs.py [output folder]

The pages are generated, never edited and never committed: the declared
keys in ``src/v2/components`` are the source. The default output folder is
``docs/v2/components`` (git-ignored).
"""
from __future__ import annotations

import inspect
import sys
from pathlib import Path
from typing import Any, List, Sequence, Tuple, Type

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.v2 import components  # noqa: E402,F401 -- importing it registers every component
from src.v2.components.base import Component, Eager, Sink, Source  # noqa: E402
from src.v2.components.registry import REGISTRY  # noqa: E402
from src.v2.job.keys import CODE, EXPRESSION, Key, Kind  # noqa: E402

DEFAULT_FOLDER = ROOT / "docs" / "v2" / "components"


def type_name(key: Key) -> str:
    """How a key's value type reads in a doc page."""
    if key.type == EXPRESSION:
        return "Python expression"
    if key.type == CODE:
        return "Python code"
    if key.type is object:
        return "any"
    return {str: "text", int: "whole number", float: "number", bool: "true/false", list: "list", dict: "object"}.get(
        key.type, getattr(key.type, "__name__", str(key.type))
    )


def shown(value: Any) -> str:
    """A default value as it would be written in a job config."""
    if value is None:
        return ""
    if isinstance(value, bool):
        return "`true`" if value else "`false`"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        escaped = escaped.replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t")
        return f'`"{escaped}"`'
    return f"`{value!r}`"


def cell(text: str) -> str:
    return " ".join(str(text).split()).replace("|", "\\|")


def supported_table(keys: Sequence[Key], prefix: str = "") -> List[str]:
    """Table rows for supported keys, nested keys included under their parent's name."""
    rows: List[str] = []
    for key in keys:
        if key.kind is not Kind.SUPPORTED:
            continue
        name = f"`{prefix}{key.name}`" + (" (required)" if key.required else "")
        aliases = ", ".join(f"`{alias}`" for alias in key.aliases)
        doc = key.doc
        if key.choices:
            doc += " One of: " + ", ".join(f"`{choice}`" for choice in key.choices) + "."
        rows.append(f"| {name} | {aliases} | {type_name(key)} | {cell(shown(key.default))} | {cell(doc)} |")
        if key.items:
            rows += supported_table(key.items, f"{prefix}{key.name}[].")
        if key.fields:
            rows += supported_table(key.fields, f"{prefix}{key.name}.")
    return rows


def kind_of(cls: Type[Component]) -> str:
    if issubclass(cls, Source):
        return "source: reads rows, takes no input"
    if issubclass(cls, Sink):
        return "sink: writes its input"
    if issubclass(cls, Eager):
        return "holds its input rows in memory while it runs"
    return "transform: stays lazy, holds no rows"


def page(cls: Type[Component]) -> str:
    """The doc page of one component class."""
    keys = cls.all_keys()
    lines = [f"# {cls.names[0]}", "", inspect.cleandoc(cls.__doc__ or ""), ""]
    lines += [f"- Type names accepted in a job config: {', '.join(f'`{name}`' for name in cls.names)}"]
    lines += [f"- Kind: {kind_of(cls)}"]
    if cls.outputs:
        ports = "; ".join(
            f"`{port}` (flow types {', '.join(f'`{flow}`' for flow in flows)})" for port, flows in cls.outputs.items()
        )
        lines += [f"- Outputs: {ports}"]
    lines += ["", "## Config keys", ""]
    rows = supported_table(keys)
    if rows:
        lines += ["| Key | v1 spelling | Value | Default | What it does |", "|---|---|---|---|---|"] + rows
    else:
        lines += ["None."]
    ignored = [key for key in keys if key.kind is Kind.IGNORED]
    if ignored:
        lines += ["", "## Accepted and ignored", "",
                  "These keys may be present; they change nothing.", ""]
        lines += [f"- {', '.join(f'`{s}`' for s in key.spellings)}: {cell(key.doc)}" for key in ignored]
    refused = [key for key in keys if key.kind is Kind.REFUSED]
    if refused:
        lines += ["", "## Refused", "",
                  "A job config that uses one of these is not run. A value that means \"off\" is accepted.", ""]
        lines += [f"- {', '.join(f'`{s}`' for s in key.spellings)}: {cell(key.reason or key.doc)}" for key in refused]
    return "\n".join(lines) + "\n"


def index(classes: Sequence[Type[Component]]) -> str:
    lines = ["# v2 components", "", "Generated by `scripts/gen_v2_docs.py` from the declared config keys.", "",
             "| Component | v1 type names | What it does |", "|---|---|---|"]
    for cls in classes:
        summary = inspect.cleandoc(cls.__doc__ or "").split("\n\n")[0]
        v1_names = ", ".join(f"`{name}`" for name in cls.names[1:])
        lines.append(f"| [{cls.names[0]}]({cls.names[0]}.md) | {v1_names} | {cell(summary)} |")
    return "\n".join(lines) + "\n"


def generate(folder: Path = DEFAULT_FOLDER) -> List[Tuple[str, str]]:
    """Write every page. Returns (file name, text) for each page written."""
    classes = sorted(REGISTRY.classes(), key=lambda cls: cls.names[0])
    pages = [("README.md", index(classes))] + [(f"{cls.names[0]}.md", page(cls)) for cls in classes]
    folder.mkdir(parents=True, exist_ok=True)
    for name, text in pages:
        (folder / name).write_text(text, encoding="utf-8")
    return pages


if __name__ == "__main__":
    target = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_FOLDER
    written = generate(target)
    print(f"wrote {len(written)} pages to {target}")
